# Main resources of the project: the Lambda function and its invocation permission.
#
# The Lambda is the core of the solution. EventBridge Schedulers are generated
# dynamically from config.json using the `generate-schedulers` CLI command
# (see src/__main__.py); they are NOT managed by Terraform directly because
# their schedule depends on the JSON configuration.
#
# Auxiliary resources (IAM, SNS, S3) live in dedicated files: iam.tf, sns.tf, s3.tf.
#
# The Lambda deployment package is generated by Terraform during `terraform apply`
# using the `archive` provider (no separate shell/zip step). The config.json is
# uploaded to S3 by Terraform.

# Build the Lambda deployment package locally via the archive provider.
# The source is the repository root so that the zip preserves the `src/` package
# prefix (required by the `src.handler.lambda_handler` runtime and its relative
# imports). Non-runtime folders are excluded. Python dependencies (boto3 is
# provided by the Lambda runtime) must be provided via a Lambda layer if needed.
data "archive_file" "lambda_package" {
  type        = "zip"
  source_dir  = var.lambda_source_path
  output_path = var.lambda_output_path
  excludes = [
    ".git",
    ".github",
    ".venv",
    "infra",
    "tests",
    "docs-sdd",
    "scripts",
    "dist",
    ".pytest_cache",
    ".gitignore",
    "config.json",
    "requirements.txt",
    "requirements-dev.txt",
    "**/__pycache__",
    "**/*.pyc",
    "**/*.egg-info",
    "**/*.md",
  ]
}

# Upload config.json to S3 bucket.
resource "aws_s3_object" "config" {
  bucket = aws_s3_bucket.config.id
  key    = "config.json"
  source = var.config_file_path
  etag   = filemd5(var.config_file_path)
}

resource "aws_lambda_function" "shutdown" {
  function_name    = local.name_prefix
  role             = aws_iam_role.lambda_role.arn
  runtime          = var.lambda_runtime
  handler          = "src.handler.lambda_handler"
  filename         = data.archive_file.lambda_package.output_path
  source_code_hash = data.archive_file.lambda_package.output_base64sha256
  timeout          = 900
  memory_size      = 256
  tags             = local.common_tags

  # Ensure the config is uploaded before creating the Lambda
  depends_on = [
    aws_s3_object.config
  ]

  environment {
    variables = {
      CONFIG_FILE                 = "s3://${aws_s3_bucket.config.id}/config.json"
      SNS_TOPIC_ARN               = aws_sns_topic.shutdown.arn
      FALLBACK_NOTIFICATION_EMAIL = var.notification_email
    }
  }
}

# Allow EventBridge Scheduler to invoke the Lambda.
resource "aws_lambda_permission" "scheduler_invoke" {
  statement_id  = "AllowEventBridgeSchedulerInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.shutdown.function_name
  principal     = "scheduler.amazonaws.com"
  source_arn    = "arn:aws:scheduler:${var.region}:${data.aws_caller_identity.current.account_id}:schedule/*"
}